# Generated by Django 5.2.3 on 2025-06-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("sale_price", models.IntegerField()),
                ("rating", models.FloatField()),
                ("feedbacks", models.IntegerField()),
            ],
        ),
    ]
